/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElIconS: typeof import('@element-plus/icons-vue')['S']
  const ElIcons: typeof import('@element-plus/icons-vue')['s']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
